### ISSUE TITLE
Pyautogui.click() not working inside ToS

### ISSUE THREAD

**Issue by aymagee92** [TreyThomas93/TOS-Auto-Export#1] opened 2021-08-29 03:21 UTC
Trey - thanks for putting this together. I spent a couple hours setting up the code and attempting to run it, but the click function will not click inside the ToS application. It successfully clicked at locations outside of the application, but just not inside the application. Can you confirm whether it's working on your end or not?

**Comment by TreyThomas93** [comment] 2021-08-29 16:54
Make sure before you start the program that you click on the TOS
application first. This sets the application as primary so the click
function will work. And are you using Mac or Windows?

**Comment by aymagee92** [comment] 2021-08-29 21:12
I'm using Windows.

I do click on it before I run the code, but I then have to click on either VSC or terminal to run the code, which makes those primary. I don't know how to get around that.

I tested this with Microsoft Word and it took two clicks but it worked. One click made Word primary, and the the other click clicked on whichever button it was aimed at. With ToS, it's refusing to become primary no matter how many times the program clicks inside it. I've tried it full screen, partial screen, multi monitors, single monitor, can't get it to work.

**Comment by TreyThomas93** [comment] 2021-08-29 21:46
Does it get the watchlist or even arrow down on the watchlists?

**Comment by aymagee92** [comment] 2021-08-29 22:09
It moves the cursor over the hamburger icon but because it doesn't successfully click to open it, all it does is move the cursor around the screen. Then the program ends.

**Comment by TreyThomas93** [comment] 2021-08-29 22:13
I am running it just fine on mine. Not sure what the problem is. Is it
fully hovering over the hamburger icon?

**Comment by TreyThomas93** [comment] 2021-08-30 01:55
Try this. https://stackoverflow.com/questions/52406707/why-pyautogui-click-not-actually-clicking

**Comment by aymagee92** [comment] 2021-08-30 18:31
Thanks for the link. The thread that was linked inside that thread helped. I had to run both programs as administrator in order to get it to recognize the click.

I'm still having some issues getting it up and running, are you open to taking a look at it? How much do you charge?

**Comment by TreyThomas93** [comment] 2021-08-30 18:46
My help is free of charge. What issues are you having?

**Comment by aymagee92** [comment] 2021-08-30 22:18
It's throwing an error at line 123. Says it cannot find the path of 'csv_files'

**Comment by TreyThomas93** [comment] 2021-08-30 22:28
Ah yes. I need to put a .gitkeep file into that directory so it can be
committed to github. For the time being, just add a directory named
csv_files at the root level. You will need to update the absolute path to
this directory as well within the code.

**Closed as completed** 2023-06-05 00:55 UTC
